/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wanthook.ij.jpacking;

import com.wanthook.ij.jpacking.function.barcodePrint;
import com.wanthook.ij.jpacking.function.httpRequest;
import com.wanthook.ij.jpacking.function.varApp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
/**
 *
 * @author wanthook
 */
public class printUlangPalet extends javax.swing.JFrame {

    private static Object[][] dataDMaterial;
    private static int packingId = 0;
    private httpRequest hR = new httpRequest();
    private DefaultTableModel modelDMaterial;
    private varApp VarApp;
    private barcodePrint bP;
    private String paletId;
    
    private static Object[] dataMat;
    /**
     * Creates new form printUlangPalet
     */
    public printUlangPalet(){}
    public printUlangPalet(varApp VarApp) {
        this.VarApp = VarApp;
        initComponents();
        paletId = "";
        
        bP = new barcodePrint(VarApp.printer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogMaterial = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        txtDMaterial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDBatch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDMaterial = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtKodeMaterial = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtWarnaMaterial = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtBatchMaterial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTipeBerat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBerat = new javax.swing.JTextField();
        txtBruto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTareLain = new javax.swing.JTextField();
        txtCones = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRegEnd = new javax.swing.JTextField();
        txtRegStart = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JTextField();

        dialogMaterial.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogMaterial.setTitle("Search Material");
        dialogMaterial.setAlwaysOnTop(true);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Material"));

        txtDMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDMaterialKeyReleased(evt);
            }
        });

        jLabel15.setText("Kode Material");

        jLabel16.setText("Batch");

        txtDBatch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBatchKeyReleased(evt);
            }
        });

        tblDMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDMaterialMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDMaterial);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel16))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtDMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogMaterialLayout = new javax.swing.GroupLayout(dialogMaterial.getContentPane());
        dialogMaterial.getContentPane().setLayout(dialogMaterialLayout);
        dialogMaterialLayout.setHorizontalGroup(
            dialogMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogMaterialLayout.setVerticalGroup(
            dialogMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Print Ulang Barcode Palet");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer-24.png"))); // NOI18N
        jButton2.setText("Cetak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Print Ulang Barcode Palet"));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Kode Material :");
        jLabel3.setMaximumSize(new java.awt.Dimension(97, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(97, 16));

        txtKodeMaterial.setEditable(false);
        txtKodeMaterial.setBackground(new java.awt.Color(211, 209, 208));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Warna Material :");

        txtWarnaMaterial.setEditable(false);
        txtWarnaMaterial.setBackground(new java.awt.Color(211, 209, 208));
        txtWarnaMaterial.setColumns(20);
        txtWarnaMaterial.setLineWrap(true);
        txtWarnaMaterial.setRows(5);
        txtWarnaMaterial.setTabSize(2);
        jScrollPane3.setViewportView(txtWarnaMaterial);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Batch Material :");
        jLabel5.setMaximumSize(new java.awt.Dimension(97, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(97, 16));

        txtBatchMaterial.setEditable(false);
        txtBatchMaterial.setBackground(new java.awt.Color(211, 209, 208));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipe Berat :");
        jLabel6.setMaximumSize(new java.awt.Dimension(97, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(97, 16));

        txtTipeBerat.setEditable(false);
        txtTipeBerat.setBackground(new java.awt.Color(211, 209, 208));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Berat Standar :");

        txtBerat.setEditable(false);
        txtBerat.setBackground(new java.awt.Color(211, 209, 208));

        txtBruto.setEditable(false);
        txtBruto.setBackground(new java.awt.Color(211, 209, 208));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Bruto :");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Tare Lain :");

        txtTareLain.setEditable(false);
        txtTareLain.setBackground(new java.awt.Color(211, 209, 208));

        txtCones.setEditable(false);
        txtCones.setBackground(new java.awt.Color(211, 209, 208));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tare Cones:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Register :");
        jLabel9.setMaximumSize(new java.awt.Dimension(97, 16));
        jLabel9.setMinimumSize(new java.awt.Dimension(97, 16));

        txtRegEnd.setEditable(false);
        txtRegEnd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegEndKeyTyped(evt);
            }
        });

        txtRegStart.setEditable(false);
        txtRegStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegStartKeyTyped(evt);
            }
        });

        jLabel2.setText("S/D");

        txtDeskripsi.setEditable(false);
        txtDeskripsi.setBackground(new java.awt.Color(211, 209, 208));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtBatchMaterial)
                        .addGap(134, 134, 134))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTareLain, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTipeBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKodeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegStart, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCones, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBatchMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipeBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTareLain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cetakPalet();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dialogMaterial.setSize(800, 350);
        dialogMaterial.setLocationRelativeTo(null);
        dialogMaterial.setVisible(true);
        setDTableMaterial();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void cetakPalet()
    {
        if(!txtKodeMaterial.getText().isEmpty())
        {
            String param = "palet_id="+paletId;
//            System.out.println(param);
            String htt = hR.httpGet("http://"+VarApp.ip+"/api/timbangan/list-timbangan?"+param,VarApp.tokken);
//            System.out.println(htt);
            if(hR.isJSONValid(htt))
            {
                JSONObject jO = new JSONObject(htt);
                JSONArray jA = jO.getJSONArray("data");
                
                Object datas[][] = new Object[jA.length()][];                
                for(int i=0 ; i<jA.length() ; i++)
                {
//                    System.out.println(VarApp.userName);
                    datas[i] = new Object[]{
                        jA.getJSONObject(i).getString("material"),
                        String.format("%010d",(int)jA.getJSONObject(i).get("no")),
                        jA.getJSONObject(i).getString("warna_cones"),
                        jA.getJSONObject(i).getString("batch"),
                        jA.getJSONObject(i).getString("mill"),
                        jA.getJSONObject(i).getString("tipe_berat"),
                        jA.getJSONObject(i).getString("deskripsi"),
                        jA.getJSONObject(i).get("qty"),
                        jA.getJSONObject(i).get("standar"),
                        jA.getJSONObject(i).get("actual"),
                        jA.getJSONObject(i).get("berat_papan"),
                        jA.getJSONObject(i).get("berat_sc"),
                        jA.getJSONObject(i).get("bruto"),
                        jA.getJSONObject(i).get("no_reg"),
                        jA.getJSONObject(i).getString("created_at"),
                    };
//                    System.out.println(datas[i].toString());
                }
//                System.out.println(datas.length);
                String pal = bP.paletBarcode(datas, paletId);
//                System.out.println(pal);
                bP.printBarcode(pal, VarApp.printer);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Respon server tidak dikenal. Hubungi pihak IT.", "Perhatian", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data belum dipilih", "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void txtRegEndKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegEndKeyTyped
        // TODO add your handling code here:
        char chr = evt.getKeyChar();

        if(!Character.isDigit(chr) && evt.getKeyCode()!=8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtRegEndKeyTyped

    private void txtRegStartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegStartKeyTyped
        // TODO add your handling code here:
        char chr = evt.getKeyChar();

        if(!Character.isDigit(chr) && evt.getKeyCode()!=8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtRegStartKeyTyped

    private void txtDMaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDMaterialKeyReleased
        // TODO add your handling code here:
        if(txtDMaterial.getText().length() > 3)
        {
            this.setDTableMaterial();
        }
    }//GEN-LAST:event_txtDMaterialKeyReleased

    private void txtDBatchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBatchKeyReleased
        // TODO add your handling code here:
        if(txtDBatch.getText().length() > 3)
        {
            this.setDTableMaterial();
        }
    }//GEN-LAST:event_txtDBatchKeyReleased

    private void tblDMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDMaterialMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2)
        {
            int row = tblDMaterial.getSelectedRow();
            dataMat = dataDMaterial[row];
//            System.out.println(dataDMaterial[row][9]);
            paletId =dataDMaterial[row][12].toString();
//            packingId = id;
            //            System.out.println(id);
            txtKodeMaterial.setText(String.valueOf(dataDMaterial[row][0]));
            txtWarnaMaterial.setText(String.valueOf(dataDMaterial[row][1]));
            txtBatchMaterial.setText(String.valueOf(dataDMaterial[row][2]));
            txtRegStart.setText(String.valueOf(dataDMaterial[row][4]));
            txtRegEnd.setText(String.valueOf(dataDMaterial[row][5]));
            
            txtTipeBerat.setText(String.valueOf(dataDMaterial[row][10]));
            txtDeskripsi.setText(String.valueOf(dataDMaterial[row][11]));
            txtBerat.setText(String.valueOf(dataDMaterial[row][6]));
            txtCones.setText(String.valueOf(dataDMaterial[row][7]));
            txtTareLain.setText(String.valueOf(dataDMaterial[row][8]));
            txtBruto.setText(String.valueOf(dataDMaterial[row][9]));

            //            txtRegister.setText(this.registerNumber(id));
            //            txtNoReg.setText(this.regNum());

            dialogMaterial.dispose();
            //            new formTimbang(id).setVisible(true);
        }
    }//GEN-LAST:event_tblDMaterialMouseClicked
    
    private void setDTableMaterial()
    {
        
        String param = "material="+txtDMaterial.getText()+
                       "&batch="+txtDBatch.getText();
//        System.out.println(param);
        String htt = hR.httpGet("http://"+varApp.ip+"/api/palet/list-palet?"+param,VarApp.tokken);
        JSONObject jO = new JSONObject(htt);
        JSONArray jA = jO.getJSONArray("data");
        printUlangPalet.dataDMaterial = null;
        
        if(jA.length()>0)
        {
            dataDMaterial = new Object[jA.length()][];
            
            for(int i=0 ; i<jA.length() ; i++)
            {
                dataDMaterial[i] = new Object[]{
                    jA.getJSONObject(i).getString("material"),
                    jA.getJSONObject(i).getString("warna_cones"),
                    jA.getJSONObject(i).getString("batch"),
                    jA.getJSONObject(i).getString("mill"),
                    String.format("%010d",(int)jA.getJSONObject(i).get("start_no")),
                    String.format("%010d",(int)jA.getJSONObject(i).get("end_no")),
                    jA.getJSONObject(i).get("tStandar"),
                    jA.getJSONObject(i).get("tTare_cones"),
                    jA.getJSONObject(i).get("tTare_lain"),
                    jA.getJSONObject(i).get("tBruto"),
                    jA.getJSONObject(i).getString("tipe_berat"),   
                    jA.getJSONObject(i).getString("deskripsi"),
                    jA.getJSONObject(i).get("id"),
                    jA.getJSONObject(i).get("start_no"),jA.getJSONObject(i).get("end_no"),
                };
            }
        }
        
        tblDMaterial.setModel(new DefaultTableModel(dataDMaterial,
                new String[]{"material",
                    "Warna Cones", 
                    "Batch", 
                    "Mill",
                    "Register Awal",
                    "Register Akhir",
                    "Total Berat Standar",
                    "Total Tare Cones", 
                    "Total Tare Lain",
                    "Total Bruto",
                    "Jenis Berat",
                    "Deskripsi"})
                {
                    boolean[] canEdit = new boolean[]{false,false,false,false,false,false,false,false,false,false, false};
                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) 
                    {
                        return canEdit [columnIndex];
                    }
                }  );  
//        tblDMaterial.clear
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogMaterial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDMaterial;
    private javax.swing.JTextField txtBatchMaterial;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtBruto;
    private javax.swing.JTextField txtCones;
    private javax.swing.JTextField txtDBatch;
    private javax.swing.JTextField txtDMaterial;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtKodeMaterial;
    private javax.swing.JTextField txtRegEnd;
    private javax.swing.JTextField txtRegStart;
    private javax.swing.JTextField txtTareLain;
    private javax.swing.JTextField txtTipeBerat;
    private javax.swing.JTextArea txtWarnaMaterial;
    // End of variables declaration//GEN-END:variables
}
